version: "3"
services:
  ftp:
    build: .
    container_name: ftp-reproduction
    image: ftp-reproduction
    ports:
      - "20:20"
      - "21:21"
      - "30000-30050:30000-30050"
    volumes:
      - ./volume/ftp:/var/ftp
      - ./volume/cert:/var/cert